/**
 * Lookup helper for the ProConnect IND-2025 series/code → description map.
 *
 * The JSON is generated by scripts/build-series-code-map.mjs from the
 * ind-2025-series-codes.csv and bundled at build time by Next.js.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const raw = require("./series-code-map.json") as Record<
  string,
  { description: string; screenTitle: string }
>

/**
 * Returns the human-readable description for a series+code pair.
 * e.g. lookupFieldDescription("s11", "c1003") → "Employer's name"
 *
 * Falls back to undefined when the code is not in the catalog.
 */
export function lookupFieldDescription(
  seriesId: string,
  codeId: string,
): { description: string; screenTitle: string } | undefined {
  return raw[`${seriesId}:${codeId}`]
}
