/**
 * Contact update suggestions — review queue API.
 *
 * GET /api/contacts/update-suggestions
 *   Lists suggestions generated by sync_lead_contact_updates() from
 *   client-provided intake-form / Calendly data that CONFLICTS with the
 *   Hub contact record. Pending first (oldest capture last), plus the 50
 *   most recently resolved for the "history" tab.
 *
 * POST /api/contacts/update-suggestions
 *   body: { action: "refresh" } — re-runs the generator on demand (it
 *   also runs automatically after every Calendly sync).
 */
import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { getAuthenticatedUser } from "@/lib/supabase/auth-helpers"

export const dynamic = "force-dynamic"

export async function GET() {
  const supabase = await createClient()
  const { data: { user } } = await getAuthenticatedUser(supabase)
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 })

  const [pendingRes, resolvedRes] = await Promise.all([
    supabase
      .from("contact_update_suggestions")
      .select(
        `id, contact_id, field, current_value, suggested_value, source,
         source_ref, source_captured_at, status, created_at,
         contact:contacts (id, full_name, primary_email)`,
      )
      .eq("status", "pending")
      .order("created_at", { ascending: false }),
    supabase
      .from("contact_update_suggestions")
      .select(
        `id, contact_id, field, current_value, suggested_value, source,
         status, resolved_at, resolved_by,
         contact:contacts (id, full_name, primary_email)`,
      )
      .neq("status", "pending")
      .order("resolved_at", { ascending: false })
      .limit(50),
  ])

  if (pendingRes.error) {
    return NextResponse.json({ error: pendingRes.error.message }, { status: 500 })
  }

  return NextResponse.json({
    pending: pendingRes.data ?? [],
    resolved: resolvedRes.data ?? [],
  })
}

export async function POST(req: Request) {
  const supabase = await createClient()
  const { data: { user } } = await getAuthenticatedUser(supabase)
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 })

  const body = await req.json().catch(() => ({}))
  if (body?.action !== "refresh") {
    return NextResponse.json({ error: "action must be 'refresh'" }, { status: 400 })
  }

  const { data, error } = await supabase.rpc("sync_lead_contact_updates")
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ result: data?.[0] ?? null })
}
