import { type NextRequest, NextResponse } from "next/server"
import { getKarbonCredentials, karbonFetchAll } from "@/lib/karbon-api"
import { tryCreateAdminClient } from "@/lib/supabase/server"

function getSupabaseClient() {
  return tryCreateAdminClient()
}

function mapKarbonContactToSupabase(contact: any) {
  // Extract business card data (primary card)
  const businessCards = Array.isArray(contact.BusinessCards) ? contact.BusinessCards : []
  const businessCard = businessCards.find((bc: any) => bc.IsPrimaryCard) || businessCards[0] || {}

  // Extract accounting detail
  const accountingDetail = contact.AccountingDetail || {}

  // Extract addresses from business card
  const addresses = businessCard.Addresses
    ? Array.isArray(businessCard.Addresses)
      ? businessCard.Addresses
      : [businessCard.Addresses]
    : []
  const primaryAddress = addresses.find((a: any) => a.Label === "Physical") || addresses[0] || {}
  const mailingAddress = addresses.find((a: any) => a.Label === "Mailing") || {}

  // Extract phone numbers from business card
  const phoneNumbers = businessCard.PhoneNumbers
    ? Array.isArray(businessCard.PhoneNumbers)
      ? businessCard.PhoneNumbers
      : [businessCard.PhoneNumbers]
    : []
  const workPhone = phoneNumbers.find((p: any) => p.Label === "Work")
  const mobilePhone = phoneNumbers.find((p: any) => p.Label === "Mobile")
  const faxPhone = phoneNumbers.find((p: any) => p.Label === "Fax")
  const primaryPhone = phoneNumbers.find((p: any) => p.Label === "Primary") || phoneNumbers[0]

  // Extract email addresses from business card
  const emailAddresses = businessCard.EmailAddresses || []
  const primaryEmail = Array.isArray(emailAddresses) ? emailAddresses[0] : emailAddresses
  const secondaryEmail = Array.isArray(emailAddresses) && emailAddresses.length > 1 ? emailAddresses[1] : null

  // Extract registration numbers - handle both single object and array
  const regNumbers = accountingDetail.RegistrationNumbers || {}
  const regNumbersArray = Array.isArray(regNumbers) ? regNumbers : regNumbers.Type ? [regNumbers] : []

  // Parse registration numbers for specific IDs
  let ein: string | null = null
  let ssnLastFour: string | null = null
  let driversLicense: string | null = null
  let passportNumber: string | null = null

  regNumbersArray.forEach((reg: any) => {
    switch (reg.Type) {
      case "Employer Identification Number (EIN)":
      case "EIN":
        ein = reg.RegistrationNumber
        break
      case "Social Security Number":
      case "SSN":
        // Only store last 4 digits for security
        ssnLastFour = reg.RegistrationNumber?.slice(-4) || null
        break
      case "Driver's License":
        driversLicense = reg.RegistrationNumber
        break
      case "Passport":
        passportNumber = reg.RegistrationNumber
        break
    }
  })

  // Name fields from Karbon Contact (full_name is auto-generated by Supabase)
  const first_name = contact.FirstName || null
  const last_name = contact.LastName || null
  const middle_name = contact.MiddleName || null
  const preferred_name = contact.PreferredName || null
  const salutation = contact.Salutation || null
  const suffix = contact.Suffix || null
  const prefix = contact.Prefix || null

  // Use Karbon's FullName field directly, fallback to constructing from parts
  const full_name = contact.FullName || [first_name, middle_name, last_name].filter(Boolean).join(" ") || null

  // Contact classification from Karbon
  const contact_type = contact.ContactType || "Individual"
  const entity_type = accountingDetail.EntityType || "Individual"
  const status = contact.Status || "Active"
  const restriction_level = contact.RestrictionLevel || null
  const is_prospect = contact.ContactType === "Prospect"

  // Avatar from Karbon
  const avatar_url = contact.AvatarUrl || null

  // Primary email and phone from Karbon Contact or BusinessCard
  const primary_email = contact.EmailAddress || primaryEmail || null
  const secondary_email = secondaryEmail || null
  const phone_primary = contact.PhoneNumber || (primaryPhone?.Number ? String(primaryPhone.Number) : null)
  const phone_mobile = mobilePhone?.Number ? String(mobilePhone.Number) : null
  const phone_work = workPhone?.Number ? String(workPhone.Number) : null
  const phone_fax = faxPhone?.Number ? String(faxPhone.Number) : null

  // Physical address from Karbon BusinessCard Addresses
  const address_line1 = primaryAddress.AddressLines || primaryAddress.Street || null
  const address_line2 = primaryAddress.AddressLine2 || null
  const city = primaryAddress.City || null
  const state = primaryAddress.StateProvinceCounty || primaryAddress.State || null
  const zip_code = primaryAddress.ZipCode || primaryAddress.PostalCode || null
  const country = primaryAddress.CountryCode || primaryAddress.Country || null

  // Mailing address from Karbon BusinessCard Addresses
  const mailing_address_line1 = mailingAddress.AddressLines || mailingAddress.Street || null
  const mailing_address_line2 = mailingAddress.AddressLine2 || null
  const mailing_city = mailingAddress.City || null
  const mailing_state = mailingAddress.StateProvinceCounty || mailingAddress.State || null
  const mailing_zip_code = mailingAddress.ZipCode || mailingAddress.PostalCode || null
  const mailing_country = mailingAddress.CountryCode || mailingAddress.Country || null

  // Date of birth from Karbon AccountingDetail
  const date_of_birth = accountingDetail.BirthDate ? accountingDetail.BirthDate.split("T")[0] : null

  // Employment from Karbon
  const occupation = contact.Occupation || accountingDetail.Occupation || null
  const employer = contact.Employer || null

  // Source/referral from Karbon
  const source = contact.Source || null
  const referred_by = contact.ReferredBy || null

  // Social links from Karbon BusinessCard
  const linkedin_url = businessCard.LinkedInLink || null
  const twitter_handle = businessCard.TwitterLink || null
  const facebook_url = businessCard.FacebookLink || null
  const website = Array.isArray(businessCard.WebSites) ? businessCard.WebSites[0] : businessCard.WebSites || null

  // Tax/Legal providers from Karbon AccountingDetail
  const tax_provider_key = accountingDetail.TaxProvider?.OrganizationKey || null
  const tax_provider_name = accountingDetail.TaxProvider?.Name || null
  const legal_firm_key = accountingDetail.LegalFirm?.OrganizationKey || null
  const legal_firm_name = accountingDetail.LegalFirm?.Name || null

  // Client owner/manager/partner keys from Karbon
  const client_owner_key = contact.ClientOwnerKey || null
  const client_manager_key = contact.ClientManagerKey || null
  const client_partner_key = contact.ClientPartnerKey || null

  // User-defined identifier from Karbon
  const user_defined_identifier = contact.UserDefinedIdentifier || null

  // Registration numbers - parsed from Karbon RegistrationNumbers
  const registration_numbers = regNumbers

  // Store full Karbon data as JSONB for reference
  const business_cards = businessCards
  const accounting_detail = accountingDetail
  const assigned_team_members = contact.AssignedTeamMembers || []

  // Tags, notes, custom fields from Karbon
  const tags = contact.Tags || []
  const notes = accountingDetail.Notes?.Body || contact.Notes || null
  const custom_fields = contact.CustomFields || {}

  // Contact preference from Karbon
  const contact_preference = contact.ContactPreference || null

  // Karbon URL and sync timestamps
  const karbon_url = `https://app2.karbonhq.com/4mTyp9lLRWTC#/contacts/${contact.ContactKey}`
  const karbon_contact_url = `https://app2.karbonhq.com/4mTyp9lLRWTC#/contacts/${contact.ContactKey}`
  const karbon_created_at = contact.CreatedDateTime || null
  const karbon_modified_at = contact.LastModifiedDateTime || null
  const last_synced_at = new Date().toISOString()
  const updated_at = new Date().toISOString()

  return {
    // Core identifiers - Karbon uses ContactKey for individuals
    karbon_contact_key: contact.ContactKey,

    full_name,

    // Name fields from Karbon Contact
    first_name,
    last_name,
    middle_name,
    preferred_name,
    salutation,
    suffix,
    prefix,

    // Contact classification from Karbon
    contact_type,
    entity_type,
    status,
    restriction_level,
    is_prospect,

    // Avatar from Karbon
    avatar_url,

    // Primary email and phone from Karbon Contact or BusinessCard
    primary_email,
    secondary_email,
    phone_primary,
    phone_mobile,
    phone_work,
    phone_fax,

    // Physical address from Karbon BusinessCard Addresses
    address_line1,
    address_line2,
    city,
    state,
    zip_code,
    country,

    // Mailing address from Karbon BusinessCard Addresses
    mailing_address_line1,
    mailing_address_line2,
    mailing_city,
    mailing_state,
    mailing_zip_code,
    mailing_country,

    // Date of birth from Karbon AccountingDetail
    date_of_birth,

    // Employment from Karbon
    occupation,
    employer,

    // Source/referral from Karbon
    source,
    referred_by,

    // Social links from Karbon BusinessCard
    linkedin_url,
    twitter_handle,
    facebook_url,
    website,

    // Tax/Legal providers from Karbon AccountingDetail
    tax_provider_key,
    tax_provider_name,
    legal_firm_key,
    legal_firm_name,

    // Client owner/manager/partner keys from Karbon
    client_owner_key,
    client_manager_key,
    client_partner_key,
    user_defined_identifier,

    // Registration numbers - parsed from Karbon RegistrationNumbers
    ein,
    ssn_last_four: ssnLastFour,
    drivers_license: driversLicense,
    passport_number: passportNumber,
    registration_numbers,

    // Store full Karbon data as JSONB for reference
    business_cards,
    accounting_detail,
    assigned_team_members,

    // Tags, notes, custom fields from Karbon
    tags,
    notes,
    custom_fields,

    // Contact preference from Karbon
    contact_preference,

    // Karbon URL and sync timestamps
    karbon_url,
    karbon_contact_url,
    karbon_created_at,
    karbon_modified_at,
    last_synced_at,
    updated_at,
  }
}

async function fetchExpandedContact(
  contactKey: string,
  credentials: { bearerToken: string; accessKey: string },
): Promise<any | null> {
  try {
    const response = await fetch(`https://api.karbonhq.com/v3/Contacts/${contactKey}?$expand=BusinessCards`, {
      headers: {
        Authorization: `Bearer ${credentials.bearerToken}`,
        AccessKey: credentials.accessKey,
        "Content-Type": "application/json",
      },
    })
    if (!response.ok) {
      return null
    }
    return await response.json()
  } catch (error) {
    return null
  }
}

export async function GET(request: NextRequest) {
  const credentials = getKarbonCredentials()

  if (!credentials) {
    return NextResponse.json(
      {
        error: "Karbon API credentials not configured",
      },
      { status: 401 },
    )
  }

  try {
    const searchParams = request.nextUrl.searchParams
    const debug = searchParams.get("debug") === "true"
    const importToSupabase = searchParams.get("import") === "true"
    const top = searchParams.get("top")
    const incrementalSync = searchParams.get("incremental") === "true"
    const expandDetails = searchParams.get("expand") === "true"

    const queryOptions: any = {}
    if (top) {
      queryOptions.top = Number.parseInt(top, 10)
    }

    // We'll do client-side filtering instead for incremental sync
    let lastSyncTimestamp: string | null = null
    if (incrementalSync && importToSupabase) {
      const supabase = getSupabaseClient()
      if (supabase) {
        const { data: lastSync } = await supabase
          .from("contacts")
          .select("karbon_modified_at")
          .not("karbon_modified_at", "is", null)
          .order("karbon_modified_at", { ascending: false })
          .limit(1)
          .maybeSingle()

        if (lastSync?.karbon_modified_at) {
          lastSyncTimestamp = lastSync.karbon_modified_at
          // Don't add filter to queryOptions - Karbon doesn't support gt operator
        }
      }
    }

    const { data: allContacts, error, totalCount } = await karbonFetchAll<any>("/Contacts", credentials, queryOptions)

    if (error) {
      return NextResponse.json({ error: `Karbon API error: ${error}` }, { status: 500 })
    }

    let contactsToProcess = allContacts
    if (incrementalSync && lastSyncTimestamp) {
      const lastSyncDate = new Date(lastSyncTimestamp)
      contactsToProcess = allContacts.filter((contact: any) => {
        if (!contact.LastModifiedDateTime) return true
        return new Date(contact.LastModifiedDateTime) > lastSyncDate
      })
      console.log(
        `[v0] Incremental sync: filtered ${allContacts.length} contacts to ${contactsToProcess.length} modified since ${lastSyncTimestamp}`,
      )
    }

    if ((expandDetails || importToSupabase) && contactsToProcess.length > 0) {
      const expandedContacts: any[] = []
      const batchSize = 10 // Process 10 at a time to avoid rate limiting

      for (let i = 0; i < contactsToProcess.length; i += batchSize) {
        const batch = contactsToProcess.slice(i, i + batchSize)
        const expandedBatch = await Promise.all(
          batch.map(async (contact: any) => {
            const expanded = await fetchExpandedContact(contact.ContactKey, credentials)
            return expanded || contact // Fall back to original if expand fails
          }),
        )
        expandedContacts.push(...expandedBatch)
      }
      contactsToProcess = expandedContacts
    }

    let importResult = null
    if (importToSupabase) {
      const supabase = getSupabaseClient()
      if (!supabase) {
        importResult = { error: "Supabase not configured" }
      } else {
        let synced = 0
        let errors = 0
        const errorDetails: string[] = []

        const batchSize = 50
        for (let i = 0; i < contactsToProcess.length; i += batchSize) {
          const batch = contactsToProcess.slice(i, i + batchSize)
          const mappedBatch = batch.map((contact: any) => ({
            ...mapKarbonContactToSupabase(contact),
            created_at: new Date().toISOString(),
          }))

          const { error: upsertError } = await supabase.from("contacts").upsert(mappedBatch, {
            onConflict: "karbon_contact_key",
            ignoreDuplicates: false,
          })

          if (upsertError) {
            console.error("[v0] Batch upsert error:", upsertError)
            errors += batch.length
            errorDetails.push(upsertError.message)
          } else {
            synced += batch.length
          }
        }

        importResult = {
          success: errors === 0,
          synced,
          errors,
          incrementalSync,
          lastSyncTimestamp,
          expandedDetails: expandDetails,
          errorDetails: errorDetails.length > 0 ? errorDetails.slice(0, 5) : undefined,
        }
      }
    }

    if (debug) {
      const uniqueContactTypes = [...new Set(contactsToProcess.map((c: any) => c.ContactType).filter(Boolean))]
      const uniqueStatuses = [...new Set(contactsToProcess.map((c: any) => c.Status).filter(Boolean))]
      const uniqueCountries = [...new Set(contactsToProcess.map((c: any) => c.Country).filter(Boolean))]
      const uniqueStates = [...new Set(contactsToProcess.map((c: any) => c.State || c.StateProvince).filter(Boolean))]

      const contactTypeBreakdown: Record<string, number> = {}
      contactsToProcess.forEach((contact: any) => {
        const ct = contact.ContactType || "Unknown"
        contactTypeBreakdown[ct] = (contactTypeBreakdown[ct] || 0) + 1
      })

      const sampleRawItems = contactsToProcess.slice(0, 3).map((contact: any) => ({
        ...contact,
        _availableFields: Object.keys(contact),
      }))

      return NextResponse.json({
        analysis: {
          totalContacts: contactsToProcess.length,
          uniqueContactTypes,
          contactTypeBreakdown,
          uniqueStatuses,
          uniqueCountries,
          uniqueStates: uniqueStates.slice(0, 20),
          sampleRawItems,
          expandedDetails: expandDetails,
        },
        importResult,
        syncInfo: {
          incrementalSync,
          lastSyncTimestamp,
          itemsFetched: contactsToProcess.length,
        },
      })
    }

    return NextResponse.json({
      contacts: contactsToProcess,
      count: contactsToProcess.length,
      totalCount: totalCount || contactsToProcess.length,
      importResult,
    })
  } catch (error) {
    console.error("[v0] Error fetching Karbon contacts:", error)
    return NextResponse.json(
      {
        error: "Failed to fetch contacts from Karbon",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}
