/**
 * Zoom AI Companion summary → client note (FALLBACK path).
 * ────────────────────────────────────────────────────────
 *
 * Primary summarization is ALFRED-over-the-transcript
 * (`lib/zoom/summarize-transcript.ts`). But not every meeting has a
 * downloadable transcript:
 *   • the host had AI Companion ON but cloud transcription OFF,
 *   • the recording is audio-only with no VTT,
 *   • Zoom's reporting window aged out the transcript file.
 *
 * When the firm's Zoom plan has AI Companion, Zoom itself generates a
 * structured meeting summary (overview + sectioned details + next
 * steps). The S2S app is scoped for `meeting:read:summary:admin` +
 * `meeting:read:list_summaries:admin`, so we can pull that summary and
 * write it to the client's profile notes as a fallback — clearly
 * labelled as Zoom-generated, NOT ALFRED-generated, so it never gets
 * confused with the higher-fidelity transcript summary.
 *
 * Guardrails (mirror the transcript summarizer):
 *   • Only ingest for meetings that are CLIENT-LINKED. We never
 *     fabricate a contact — same rule as the triage/summary code.
 *   • Never override the transcript summary: if a transcript with text
 *     exists for the meeting, skip (the transcript path will/has run).
 *   • Idempotent: the resulting note id is stashed on
 *     `zoom_meetings.raw_data.alfred_ai_summary_note_id` so re-runs
 *     UPDATE the same note instead of piling up duplicates. No schema
 *     change required.
 */

import type { SupabaseClient } from "@supabase/supabase-js"
import type { ZoomApiFetcher } from "./process-meeting-participants"

// ─── Zoom summary shape (same for webhook payload + REST response) ───

interface ZoomMeetingSummary {
  meeting_uuid?: string
  meeting_id?: string | number
  summary_title?: string
  summary_overview?: string
  summary_details?: Array<{ label?: string; summary?: string }>
  next_steps?: string[]
  summary_start_time?: string
}

export interface AiSummaryIngestResult {
  scanned: number
  ingested: number
  updated: number
  skippedHasTranscript: number
  skippedNoClient: number
  skippedNoSummary: number
  errors: Array<{ meeting_id: string; error: string }>
}

function encodeMeetingUuid(uuid: string): string {
  // Per Zoom docs, UUIDs containing `/` or starting with `/` must be
  // double URL-encoded in the path.
  return encodeURIComponent(encodeURIComponent(uuid))
}

/** Pull the AI Companion summary for one meeting via the REST API. */
async function fetchZoomAiSummary(
  zoomGet: ZoomApiFetcher,
  meeting: { zoom_uuid: string | null; zoom_meeting_id: string | number | null },
): Promise<ZoomMeetingSummary | null> {
  const tryOne = async (idSegment: string): Promise<ZoomMeetingSummary | null> => {
    const res = await zoomGet(`https://api.zoom.us/v2/meetings/${idSegment}/meeting_summary`)
    if (res.status === 404) return null
    if (!res.ok) {
      const body = await res.text().catch(() => "")
      throw new Error(`meeting_summary ${res.status}: ${body.slice(0, 160)}`)
    }
    return (await res.json()) as ZoomMeetingSummary
  }

  // Prefer the UUID (unique per occurrence); fall back to the numeric id.
  if (meeting.zoom_uuid) {
    const byUuid = await tryOne(encodeMeetingUuid(meeting.zoom_uuid))
    if (byUuid) return byUuid
  }
  if (meeting.zoom_meeting_id != null) {
    return tryOne(String(meeting.zoom_meeting_id))
  }
  return null
}

/** Render a Zoom AI summary as a markdown note body. */
function renderAiNote(summary: ZoomMeetingSummary, startTime: string | null): string {
  const lines: string[] = []
  if (summary.summary_overview?.trim()) {
    lines.push(summary.summary_overview.trim())
    lines.push("")
  }
  const details = (summary.summary_details ?? []).filter((d) => d?.summary?.trim())
  if (details.length > 0) {
    for (const d of details) {
      if (d.label?.trim()) lines.push(`**${d.label.trim()}**`)
      lines.push(d.summary!.trim())
      lines.push("")
    }
  }
  const steps = (summary.next_steps ?? []).filter((s) => s?.trim())
  if (steps.length > 0) {
    lines.push("**Next steps**")
    for (const s of steps) lines.push(`- ${s.trim()}`)
    lines.push("")
  }
  const dateStr = startTime
    ? new Date(startTime).toLocaleDateString("en-US", { dateStyle: "medium" })
    : null
  const footer: string[] = []
  if (dateStr) footer.push(`Meeting: ${dateStr}`)
  footer.push("Generated by Zoom AI Companion (no transcript available)")
  lines.push(`_${footer.join(" · ")}_`)
  return lines.join("\n").trim()
}

/** Resolve the best client contact for a meeting (confirmed > confidence). */
async function resolveContactId(
  admin: SupabaseClient,
  zoomMeetingId: string,
): Promise<string | null> {
  const { data: links } = await admin
    .from("zoom_meeting_clients")
    .select("contact_id, confidence, needs_review")
    .eq("zoom_meeting_id", zoomMeetingId)
    .not("contact_id", "is", null)

  if (!links || links.length === 0) return null
  const sorted = [...links].sort((a, b) => {
    if (!!a.needs_review !== !!b.needs_review) return a.needs_review ? 1 : -1
    return (b.confidence ?? 0) - (a.confidence ?? 0)
  })
  return sorted[0]?.contact_id ?? null
}

/**
 * Scan recent client-linked meetings that lack a transcript and ingest
 * their Zoom AI Companion summary as a fallback note. Bounded by
 * `limit` ingests; idempotent.
 */
export async function ingestPendingZoomAiSummaries(
  admin: SupabaseClient,
  zoomGet: ZoomApiFetcher | null,
  opts: { limit?: number; sinceDays?: number } = {},
): Promise<AiSummaryIngestResult> {
  const limit = Math.max(1, Math.min(opts.limit ?? 10, 50))
  const sinceDays = Math.max(1, Math.min(opts.sinceDays ?? 365, 1000))
  const result: AiSummaryIngestResult = {
    scanned: 0,
    ingested: 0,
    updated: 0,
    skippedHasTranscript: 0,
    skippedNoClient: 0,
    skippedNoSummary: 0,
    errors: [],
  }

  const sinceIso = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000).toISOString()

  // Candidate meetings: recent, with a client link. We scan a wider set
  // than `limit` because many will be skipped (already have a transcript
  // or already summarized).
  const { data: meetings, error } = await admin
    .from("zoom_meetings")
    .select("id, zoom_uuid, zoom_meeting_id, topic, start_time, raw_data")
    .gte("start_time", sinceIso)
    .order("start_time", { ascending: false })
    .limit(limit * 6)

  if (error) {
    result.errors.push({ meeting_id: "select", error: error.message })
    return result
  }

  for (const m of meetings ?? []) {
    if (result.ingested + result.updated >= limit) break
    result.scanned += 1
    const meetingId = m.id as string
    const raw = (m.raw_data as Record<string, unknown> | null) ?? {}

    try {
      // 1. Skip if a transcript with text already exists — that path wins.
      if (m.zoom_meeting_id != null) {
        const { data: t } = await admin
          .from("zoom_transcripts")
          .select("id")
          .eq("zoom_meeting_id", m.zoom_meeting_id)
          .not("text_content", "is", null)
          .limit(1)
          .maybeSingle()
        if (t) {
          result.skippedHasTranscript += 1
          continue
        }
      }

      // 2. Must be client-linked.
      const contactId = await resolveContactId(admin, meetingId)
      if (!contactId) {
        result.skippedNoClient += 1
        continue
      }

      // 3. Get the summary: prefer the webhook-stored object, else REST.
      let summary = (raw.summary as ZoomMeetingSummary | undefined) ?? null
      if (!summary && zoomGet) {
        summary = await fetchZoomAiSummary(zoomGet, {
          zoom_uuid: (m.zoom_uuid as string | null) ?? null,
          zoom_meeting_id: (m.zoom_meeting_id as string | number | null) ?? null,
        })
      }
      const hasContent =
        !!summary &&
        (!!summary.summary_overview?.trim() ||
          (summary.summary_details?.some((d) => d?.summary?.trim()) ?? false))
      if (!summary || !hasContent) {
        result.skippedNoSummary += 1
        continue
      }

      const startTime = (m.start_time as string | null) ?? null
      const body = renderAiNote(summary, startTime)
      const title = `Meeting summary (Zoom AI)${
        startTime
          ? ` — ${new Date(startTime).toLocaleDateString("en-US", { dateStyle: "medium" })}`
          : ""
      }`

      const existingNoteId = (raw.alfred_ai_summary_note_id as string | undefined) ?? null
      if (existingNoteId) {
        const { error: upErr } = await admin
          .from("notes")
          .update({
            title,
            content: body,
            content_type: "markdown",
            note_type: "meeting_summary",
            updated_at: new Date().toISOString(),
          })
          .eq("id", existingNoteId)
        if (upErr) throw new Error(`notes update: ${upErr.message}`)
        result.updated += 1
      } else {
        const { data: noteRow, error: insErr } = await admin
          .from("notes")
          .insert({
            contact_id: contactId,
            title,
            content: body,
            content_type: "markdown",
            note_type: "meeting_summary",
            is_pinned: false,
            tags: ["zoom-ai-summary"],
          })
          .select("id")
          .single()
        if (insErr) throw new Error(`notes insert: ${insErr.message}`)

        // Stash the note id so future runs update rather than duplicate.
        await admin
          .from("zoom_meetings")
          .update({
            raw_data: { ...raw, alfred_ai_summary_note_id: noteRow.id },
            updated_at: new Date().toISOString(),
          })
          .eq("id", meetingId)
        result.ingested += 1
      }
    } catch (err) {
      result.errors.push({
        meeting_id: meetingId,
        error: err instanceof Error ? err.message : "unknown",
      })
    }
  }

  return result
}
