-- Motta Alliance — internal comic-book series
--
-- Persists newly-issued editions of the firm's in-house comic series so the
-- Motta Alliance gallery page can mix the original seeded blob-hosted PDFs
-- with new editions uploaded through the in-app "Issue New Edition" dialog.
-- Each row is one issue; the PDF lives in Vercel Blob and is referenced by
-- URL so the gallery's Read/Download buttons keep working unchanged.
--
-- ALFRED Ai reads the uploaded PDF (via Claude) and stores both a short
-- "preview" summary (used in the broadcast email + on the cover card) and
-- the rendered email HTML it sent out, so we have a historical record of
-- what was published alongside the actual PDF.

CREATE TABLE IF NOT EXISTS motta_alliance_issues (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Stable URL-safe identifier — also used as the suggested download
  -- filename on the gallery card. Generated by the API from the title +
  -- a short random suffix to keep it unique across re-issues with the
  -- same name.
  slug TEXT NOT NULL UNIQUE,

  -- Top-line series label. Defaults to "Motta Alliance" but kept as a
  -- text column so a future "Hero Volume" or one-off arc can be filed
  -- under a different label without a schema change.
  series TEXT NOT NULL DEFAULT 'Motta Alliance',

  -- Free-form issue identifier ("Issue 3", "Vol. 2", "Special"). Not a
  -- numeric column because the existing series mixes "Issue N" with
  -- "Vol. N" formatting and we want the user to keep control of the
  -- on-cover string.
  issue_number TEXT NOT NULL,

  title TEXT NOT NULL,
  arc TEXT,
  tagline TEXT,

  -- Featured characters list. Stored as a Postgres text[] so the
  -- gallery can render each one as a Badge chip without parsing.
  characters TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],

  -- Blob storage. URL is what the gallery reads/downloads; pathname is
  -- kept around in case we ever need to `del()` the file (e.g. an
  -- accidental upload).
  pdf_url TEXT NOT NULL,
  pdf_pathname TEXT,
  pdf_size_bytes BIGINT,

  -- Visual variant for the cover card. Free-form text so future
  -- variants can be added without a CHECK constraint migration; the
  -- React component falls back to "olive" for unknown values.
  variant TEXT NOT NULL DEFAULT 'olive',

  -- Claude-generated outputs. `ai_summary` is the short teaser used on
  -- the cover card + email banner; `ai_email_body_html` is the full
  -- rendered HTML we sent to Resend so we can replay it later.
  ai_summary TEXT,
  ai_email_body_html TEXT,

  -- Issuance + delivery audit trail.
  created_by_id UUID REFERENCES team_members(id) ON DELETE SET NULL,
  created_by_name TEXT,
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  email_sent_at TIMESTAMPTZ,
  email_attempted_count INTEGER NOT NULL DEFAULT 0,
  email_sent_count INTEGER NOT NULL DEFAULT 0,
  email_skipped_count INTEGER NOT NULL DEFAULT 0,
  email_error TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ordered timeline lookup — the gallery sorts newest first.
CREATE INDEX IF NOT EXISTS idx_motta_alliance_issues_published_at
  ON motta_alliance_issues (published_at DESC);

-- Lookup by series so a future "show only Hero Volumes" filter is cheap.
CREATE INDEX IF NOT EXISTS idx_motta_alliance_issues_series
  ON motta_alliance_issues (series);

-- updated_at maintenance trigger. Mirrors the pattern used elsewhere in
-- the schema (see notification_preferences) so the column stays accurate
-- across in-place edits.
CREATE OR REPLACE FUNCTION motta_alliance_issues_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_motta_alliance_issues_updated_at ON motta_alliance_issues;
CREATE TRIGGER trg_motta_alliance_issues_updated_at
  BEFORE UPDATE ON motta_alliance_issues
  FOR EACH ROW EXECUTE FUNCTION motta_alliance_issues_set_updated_at();

-- RLS — match the firm-wide "authenticated team members can read all,
-- service role writes" pattern used for most internal-content tables.
ALTER TABLE motta_alliance_issues ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS motta_alliance_issues_read_authenticated ON motta_alliance_issues;
CREATE POLICY motta_alliance_issues_read_authenticated
  ON motta_alliance_issues FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS motta_alliance_issues_write_service ON motta_alliance_issues;
CREATE POLICY motta_alliance_issues_write_service
  ON motta_alliance_issues FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
