-- 418: Let a portal detail change become an approvable suggestion.
--
-- Both halves of this loop already existed and were never joined:
--   · The portal's My Account page submits changes, but POST
--     /api/client-portal/client-info only wrote them as a chat message,
--     which nothing can approve.
--   · contact_update_suggestions (scripts/384) already has accept/dismiss
--     routes and an admin page at /admin/contact-updates -- but its CHECK
--     constraints only admitted the two lead surfaces that existed then.
--
-- This widens those constraints so the portal can be a third source, and
-- so a mailing address can be suggested at all.
--
-- Note on 'address': the portal shows the mailing address as ONE line,
-- built by joining line1/city/state/zip with ", ". The accept route parses
-- it back on exactly that shape and refuses anything it can't split
-- confidently, rather than guessing a client's address into the wrong
-- columns.

alter table public.contact_update_suggestions
  drop constraint if exists contact_update_suggestions_field_check;
alter table public.contact_update_suggestions
  add constraint contact_update_suggestions_field_check
  check (field in ('name', 'email', 'phone', 'state', 'address'));

alter table public.contact_update_suggestions
  drop constraint if exists contact_update_suggestions_source_check;
alter table public.contact_update_suggestions
  add constraint contact_update_suggestions_source_check
  check (source in ('intake_form', 'calendly', 'client_portal'));

comment on column public.contact_update_suggestions.source is
  'Where the suggested value came from: intake_form / calendly (generated by sync_lead_contact_updates) or client_portal (submitted by the client themselves from My Account).';
